Added small info about a specific tea

diff --git a/tea b/tea
--- a/tea
+++ b/tea
@@ -89,21 +89,33 @@ function edit_notes {
         [ -z "$uid" ] && die "Couldn't find a log entry with that uid."
     fi
     
-    if tmpfile=$(mktemp -q /tmp/teanotes.XXXXX); then
-        [ -z "$EDITOR" ] && die "NO \$EDITOR set."
-        sqlite3 "$DB" "select notes from log where uid = '$(escape_sqlite "$uid")'" > $tmpfile
-        $EDITOR "$tmpfile"
-        notes="$(cat "$tmpfile")"
-        sqlite3 "$DB" << SQL
-            update log set notes = '$(escape_sqlite "$notes")' where uid = '$uid';
+    tmpfile=$(_try_create_tempfile) || die "$0: Couldn't create tempfile"
+    
+    sqlite3 "$DB" "select notes from log where uid = '$(escape_sqlite "$uid")'" > $tmpfile
+    $EDITOR "$tmpfile"
+    notes="$(cat "$tmpfile")"
+    sqlite3 "$DB" << SQL
+        update log set notes = '$(escape_sqlite "$notes")' where uid = '$uid';
 SQL
-    else
-        die "$0: Couldn't create tempfile"
-    fi
+
 }
 
 function quick_log {
     sqlite3 "$DB" "select tea, date, uid from log order by date desc limit 10"
+}
+
+function info_tea {
+	tea="$(list_teas)"
+	tea="$(escape_sqlite "$tea")"
+	[ -z "$tea" ] && exit 0
+	total="$(sqlite3 "$DB" "select sum(amount) from teas where name = '$tea'")"
+	drank="$(sqlite3 "$DB" "select sum(amount) from log where tea = '$tea'")"
+    if [ -z "$drank" ]; then
+        echo "Of ${total}g bought you drank nothing."
+    else
+        left="$(echo - | awk "{print $total - $drank}")"
+        echo "Of ${total}g bought you drank ${drank}g. ${left}g left."
+    fi
 }
 
 [ -f "$DB" ] || sqlite3 "$DB" << SQL
@@ -138,6 +150,9 @@ case "$1" in
     ;;
     lg)
     quick_log
+    ;;
+    info)
+    info_tea
     ;;
     *)
     drink_tea_fzy
